### ISSUE TITLE
Illegal mirroring vertices 

### ISSUE THREAD

**Issue by makoto-unity** [unity3d-jp/BlendShapeBuilder#2]
On VertexTweaker window, set Move with "Soft Move".
Change Mirroring Direction to "Right To Left".
Move some vertices on right side, then you can see strange mesh on the other side.

macOS High Sierra 10.13.3
Unity Editor 2017.3.0f3

![blendshapebuilder01](https://user-images.githubusercontent.com/2757441/36156169-a8252166-1119-11e8-8e56-e48015d434b8.gif)

**Comment by i-saint** [comment]
its's a known issue, I know it's serious bug, but difficult to fix... (see #1. there are other known issues)

詳細 (面倒なので日本語)
ミラーリングの頂点の関連付けは、現在頂点の位置と法線だけで判定しています。しかし、これだけだと位置と法線が完全に同じ頂点があったとき誤認が発生します。報告の問題はこれが原因です。

これを解決するには、頂点単位ではなく、面単位で関連付けをしないといけないのですが、困ったことに三角形化した状態だと対象になっていないことが多いのです。(下図)
完全な解決には三角形化前の多角形のデータが必要なのですが、Unity からそれを取得する手段はありません。なので、なんか代替案はないかと今考えているというのが現状です。

メタセコイア上のミラーリングしたモデル
![mirror_mq](https://user-images.githubusercontent.com/1488611/36158422-a22184b6-111f-11e8-82ac-c25c98401f1e.png)

上モデルを Unity に持ってきた図。対称になっていない
![mirror_unity1](https://user-images.githubusercontent.com/1488611/36158446-b04190f4-111f-11e8-92a2-33ef69a647b1.png)

手動で対称にした図。こうなっててほしい…
![mirror_unity2](https://user-images.githubusercontent.com/1488611/36158855-add9211e-1120-11e8-9765-bb1b80930cf6.png)

**Comment by i-saint** [comment]
今思いつきましたが、もう Unity 上でモデルをばっさり半分切り捨てて作り直した方がいいかもしれない。次のバージョンでそうしてみます。

**Comment by makoto-unity** [comment]
あ、なるほど。そういうことでしたか。把握しました。
作り直し案良いですね。問題ないかと思います。

Known issue ということでクローズします。
